baseURL: "https://blackmaple.me/"
title: BlackMaple's Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-F5WCWXDYXT
disqusShortname: yaoandy107

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: BlackMaple's Blog
    description: "記錄學習的點點滴滴"
    keywords: [Blog, BlackMaple]
    author: 姚韋辰（Andy Yao）
    # author: ["Me", "You"] # multiple authors
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false
    likerID: "yaoandy107"

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicon.ico"
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        apple_touch_icon: "apple-touch-icon.png"
        # safari_pinned_tab: "<link / abs url>"

    label:
        text: "BlackMaple's Blog"
        # icon: /apple-touch-icon.png
        # iconHeight: 35

    # profile-mode
    profileMode:
        enabled: false # needs to be explicitly set
        title: BlackMaple's Blog
        subtitle: "記錄學習的點點滴滴"
        # imageUrl: "<img location>"
        # imageWidth: 120
        # imageHeight: 120
        # imageTitle: my image
        buttons:
            - name: 查看文章
              url: posts

    # home-info mode
    homeInfoParams:
        Title: "Hi, I'm Andy Yao \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: "twitter"
          url: "https://twitter.com/yaoandy107"
        - name: "github"
          url: "https://github.com/yaoandy107"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/yaoandy107/"
        - name: "email"
          url: "mailto:yaoandy107@gmail.com"

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"
    #     bing:
    #         SiteVerificationTag: "XYZabc"
    #     yandex:
    #         SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page

    editPost:
        URL: "https://github.com/yaoandy107/hugo-blog/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: posts
          name: 文章
          url: /posts/
          weight: 8
        - identifier: archives
          name: 目錄
          url: /archives/
          weight: 9
        - identifier: categories
          name: 分類
          url: /categories/
          weight: 10
        # - identifier: tags
        #   name: Tags
        #   url: /tags/
        #   weight: 20
        - identifier: search
          name: 搜尋
          url: /search/
          weight: 25
        # - identifier: example
        #   name: example.org
        #   url: https://example.org
        #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# Disqus comments
disqusShortname: yaoandy107

permalinks:
  posts: "/:filename/"